name: Auto-Merge Releases

on:
  push:
    branches:
      - release**

jobs:
  auto-merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract branch name
        id: branch_name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Merge branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token
        run: |
          filename="releases.txt"

          if [ -e "$filename" ]; then
              rm "$filename"
          fi

          git pull
          for remotebranch in `git branch -r | grep release | grep -v ${{ steps.branch_name.outputs.branch }}`; do git branch --track ${remotebranch#origin/} $remotebranch; done
          git branch --list "release*"
          git branch --list "release*" >> "$filename"

          # Loop through each line of the file
          prev_branch=${{ steps.branch_name.outputs.branch }}
          while IFS= read -r line || [[ -n "$line" ]]; do
              # Process each line here
              line="${line:2}"
              echo "Processing line: $line"

              if [ "$line" <= "${{ steps.branch_name.outputs.branch }}" ]; then
                  continue
              fi

              git checkout $line
              git pull origin "$prev_branch"
              git merge --no-ff origin/"$prev_branch" -m "Automated merge from $prev_branch"
              git push origin $line

              prev_branch=$line
          done < "$filename"

          rm "$filename"
